# docker-compose.yml (Финальная, простая версия)

services:
  backend:
    build: ./backend
    container_name: ai_furniture_backend
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: ai_furniture_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules